---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Image:
    Type: String
    Default: 811286505646.dkr.ecr.eu-west-1.amazonaws.com/traineeship-rob:latest
    Description: Full name of the image in ECR
  Cluster:
    Type: String
    Default: rob-ecs-cluster
    Description: Full name of the ECS cluster
Resources:
  EcsServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PullImage
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: '*'
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "EC2"
        - "FARGATE"
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      TaskRoleArn: !GetAtt EcsServiceRole.Arn
      ExecutionRoleArn: !GetAtt EcsServiceRole.Arn
      ContainerDefinitions:
        - Name: "traineeship"
          Image: !Ref Image
          Cpu: 256
          Memory: 512
          Essential: true
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt SecurityGroup.GroupId
          Subnets:
            - subnet-93c9def5
            - subnet-6f247435
            - subnet-29cc2a62
